version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: sharumario/yamdb_final:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static/redoc.yaml:/var/html/static/redoc.yaml
      - ./static/data/category.csv:/var/html/static/data/category.csv
      - ./static/data/comments.csv:/var/html/static/data/comments.csv
      - ./static/data/genre_title.csv:/var/html/static/data/genre_title.csv
      - ./static/data/genre.csv:/var/html/static/data/genre.csv
      - ./static/data/review.csv:/var/html/static/data/review.csv
      - ./static/data/titles.csv:/var/html/static/data/titles.csv
      - ./static/data/users.csv:/var/html/static/data/users.csv
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  static_value:
  media_value: